a=input('Digite algo para saber as suas informaçoes ')
print('O tipo primitivo do digitado é', type(a))
print('Só tem espaçoa', a.isspace())
print('É um numero?', a.isnumeric())
print('É um alfabeto?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Esta em maiuscula', a.isupper())
print('Esta em minuscula', a.islower())
print('Esta capitalizada?', a.istitle())